FROM node:lts-alpine

WORKDIR /app

COPY ./bondflix-spa-service/package.json .

COPY ./bondflix-spa-service/yarn.lock .

RUN yarn install

COPY ./bondflix-spa-service .

EXPOSE 5173

CMD ["yarn", "dev"]